### ISSUE TITLE
Fatal error is trying to delete folder

### ISSUE THREAD

**Issue by skywurz** [skywurz/PiCam-Gps#11]
Traceback (most recent call last):
File "scripts/master.py", line 618, in <module>
purge()
File "scripts/master.py", line 198, in purge
os.remove(oldest)
IsADirectoryError: [Errno 21] Is a directory: 'usbstore/System Volume Information'

**Comment by skywurz** [comment]
I think line 189  needs to be changed to usbstore from localstore this will cause the match to happen . this was imputed wrong because I missed it when I copy pastaed the code to duplicate it for another purge task.

**Comment by skywurz** [comment]
a better solution would be to check to make sure that the oldest file gatherer does not grab folders
